name: 'Check PR for SemVer Label'
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  pull-requests: read
  contents: read

jobs:
  semver-check:
    name: 'Check PR for SemVer Label'
    if: |
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Parse the SemVer label
        id: label
        uses: UKHomeOffice/match-label-action@a8e8e2690df0a1f72550875a29a73574fdefe5ad
        with:
          labels: minor,major,patch
          mode: singular

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeOffice/semver-calculate-action@fd7e1629eda3b5d3cd037d4145d49db12a352c8e
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}