name: Validate Terraform with Trivy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  RunTerraformValidation:
    name: Run Terraform SAST
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # Results have to be a table as the organisation does not have Advanced Security license.
      - name: Terraform Trivy Scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          scan-type: 'config'
          exit-code: '1'